export const families = [ //TODO {nome: cervi, name: deers}
  'cervi',
  'lupi',
  'insetti',
  'rettili',
  'uccelli',
  'robots',
  'scoiattoli',
  'rocce',
  'nessuna'
];
export const sigils = [
  'alarm',
  'apple',
  'atk2',
  'atk3',
  'bells',
  'blockFly',
  'bloodLust',
  'bomb',
  'boneDigger',
  'degnoSacr',
  'doubleDeath',
  'egg',
  'evolve',
  'fantasma',
  'fly',
  'fragile',
  'gemme',
  'guardian',
  'immortal',
  'infSacrifice',
  'leader',
  'looter',
  'magicHand',
  'push',
  'scavenger',
  'shield',
  'smell',
  'snakeBomb',
  'sniper',
  'spikes',
  'trap',
  'turret',
  'vampire',
  'water',
  'random',
];

export const sigil_def = [
  { name: 'alarm', trad: 'aaa' },
  { name: 'apple', trad: 'aaa' },
  { name: 'atk2', trad: 'aaa' },
  { name: 'atk3', trad: 'aaa' },
  { name: 'bells', trad: 'aaa' },
  { name: 'blockFly', trad: 'aaa' },
  { name: 'bloodLust', trad: 'aaa' },
  { name: 'bomb', trad: 'aaa' },
  { name: 'boneDigger', trad: 'aaa' },
  { name: 'degnoSacr', trad: 'on sacrificing it generates 3 blood' },
  { name: 'doubleDeath', trad: 'aaa' },
  { name: 'egg', trad: 'aaa' },
  { name: 'evolve', trad: 'evolve itself in a stronger form at the start of its next turn' },
  { name: 'fantasma', trad: 'aaa' },
  { name: 'fly', trad: 'it can attack directly the opponent (but still be blocked by the block sigil)' },
  { name: 'fragile', trad: 'destroy itself at the start of its next turn' },
  { name: 'gemme', trad: 'aaa' },
  { name: 'guardian', trad: 'aaa' },
  { name: 'immortal', trad: 'aaa' },
  { name: 'infSacrifice', trad: 'aaa' },
  { name: 'leader', trad: 'aaa' },
  { name: 'looter', trad: 'aaa' },
  { name: 'magicHand', trad: 'aaa' },
  { name: 'push', trad: 'Inverts position with the card at its right' },
  { name: 'random', trad: 'aaa' },
  { name: 'scavenger', trad: 'aaa' },
  { name: 'shield', trad: 'aaa' },
  { name: 'smell', trad: 'aaa' },
  { name: 'snakeBomb', trad: 'on death gifts 3 cards from your deck to your opponent' },
  { name: 'sniper', trad: 'aaa' },
  { name: 'spikes', trad: 'when being attacked, inflicts 1 damage to the attacker' },
  { name: 'trap', trad: 'aaa' },
  { name: 'turret', trad: 'aaa' },
  { name: 'vampire', trad: 'aaa' },
  { name: 'water', trad: 'aaa' }
];

// this card is not sacrificable